In [2]:
from hopfield import *

waga1 = waga[0]
print("Wagi pierwszego neuronu:")
print(waga1.reshape(5,5))

Wagi pierwszego neuronu:
[[ 0.      0.0016 -0.0048 -0.0016  0.0016]
 [-0.0016  0.0048 -0.0048  0.0016 -0.0016]
 [-0.0048 -0.0016 -0.0016 -0.0048 -0.0048]
 [-0.0016  0.0048 -0.0048  0.0016 -0.0016]
 [ 0.0016  0.0016 -0.0048 -0.0016  0.0016]]
