In [1]:
#Należy za pomocą podanego algorytmu proszę określić miarę (nie)podobieństwa obustronnego pomiędzy pierwszym  znakiem testowym (znaki_tst{1}) przesuniętym w lewo o 1, 
#a wszystkimi znakami wzorcowymi (znaki_wz{*}). Należy użyć miary odległości Euklidesowej. Proszę pokazać ten obraz jak będzie wyglądał po przesunięciu i miary (nie) podobieństwa.

from zachl_dop import *

znaki_tst1_roll = np.roll(znaki_tst1, -1)

print(f'Tablica znaki_tst1 po przesunięciu: \n{znaki_tst1_roll}')

Tablica znaki_tst1 po przesunięciu: 
[[0 0 0 0]
 [0 1 1 0]
 [1 1 1 0]
 [0 0 1 0]
 [0 0 1 0]]


In [2]:
miara1_roll_euk_babb = miara_niepodobienstwa(znaki_tst1_roll, znaki_wz1, 'euk')
miara1_roll_euk_bbba = miara_niepodobienstwa(znaki_wz1, znaki_tst1_roll, 'euk')
print(f'Miara niepodobieństwa obustronnego znaki_tst1_roll - znaki_wz1, miara Euklidesowa: {miara1_roll_euk_babb}, {miara1_roll_euk_bbba}, {miara_niepodobienstwa_obustronnego(miara1_roll_euk_babb, miara1_roll_euk_bbba)}')

miara2_roll_euk_babb = miara_niepodobienstwa(znaki_tst1_roll, znaki_wz2, 'euk')
miara2_roll_euk_bbba = miara_niepodobienstwa(znaki_wz2, znaki_tst1_roll, 'euk')
print(f'Miara niepodobieństwa obustronnego znaki_tst1_roll - znaki_wz2, miara Euklidesowa: {miara2_roll_euk_babb}, {miara2_roll_euk_bbba}, {miara_niepodobienstwa_obustronnego(miara2_roll_euk_babb, miara2_roll_euk_bbba)}')

miara3_roll_euk_babb = miara_niepodobienstwa(znaki_tst1_roll, znaki_wz3, 'euk')
miara3_roll_euk_bbba = miara_niepodobienstwa(znaki_wz3, znaki_tst1_roll, 'euk')
print(f'Miara niepodobieństwa obustronnego znaki_tst1_roll - znaki_wz3, miara Euklidesowa: {miara3_roll_euk_babb}, {miara3_roll_euk_bbba}, {miara_niepodobienstwa_obustronnego(miara3_roll_euk_babb, miara3_roll_euk_bbba)}')

Miara niepodobieństwa obustronnego znaki_tst1_roll - znaki_wz1, miara Euklidesowa: 5.0, 5.414213562373095, -10.414213562373096
Miara niepodobieństwa obustronnego znaki_tst1_roll - znaki_wz2, miara Euklidesowa: 5.0, 10.414213562373096, -15.414213562373096
Miara niepodobieństwa obustronnego znaki_tst1_roll - znaki_wz3, miara Euklidesowa: 3.0, 9.414213562373096, -12.414213562373096
